### ISSUE TITLE
Installation steps not very clear 

### ISSUE THREAD

**Issue by mylastore** [Ymple/ymple-ecommerce#42]
I guess one has to run sails lift and than the installation link provided. I get this error when trying to sails lift Error: Cannot find module '../build/Release/bson'

**Comment by fabienthetis** [comment]
i updated the version to fix this error. Let me know if you have it again. Thanks

**Comment by mylastore** [comment]
Will test tonight, I am new to GitHub can I help on the CSS?

**Comment by mylastore** [comment]
now I get this

Setting it for you this time, but note that the new `afterDisconnect` now receives an additional final argument (a callback).
More info: http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.sockets.html
sails.config.connections
sails.config.connections
sails.config.connections
sails.config.connections
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at Timeout.tooLong [as _onTimeout] (/Users/oscarquinteros/Downloads/ymple-ecommerce-master/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by fabienthetis** [comment]
It seems that the match between your configuration and the Mongodb instance in not proper. Be sure to run the mongodb instance first and double check your sails configuration for the database mongodb.

**Comment by mylastore** [comment]
You are right somehow my database is not saving for some reason on my Mac. Thank you so much let me figure this out.

**Comment by mylastore** [comment]
I am now connecting to the database but still get this errors. 

Error occurred in session middleware :: 'Error: Cannot determine state of server\n at canCheckoutReader

**Comment by mylastore** [comment]
using sails-disk a database i get this.
START]: firstInstallation
(node:1787) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: double colon in host identifier
(node:1787) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mylastore** [comment]
still can't connect to local mongodb, remote mongodb nor localdisk 

error: Error: The hook `orm` is taking too long to load.

**Comment by fabienthetis** [comment]
Which value did you set as host for the mongo configuration ? 

mongodbServer: {
    adapter: 'sails-mongo',
    host: 'localhost',...}

**Comment by mylastore** [comment]
mongodbServer: {
    adapter: 'sails-mongo',
    host: 'localhost',
    port: 27017,

   database: 'sails-shop'
 },

**Comment by fabienthetis** [comment]
Which version of mongodb do you have  ?

**Comment by mylastore** [comment]
db version v3.4.0

**Comment by fabienthetis** [comment]
Try to add this configuration in env/development.js and env/production.js
module.exports = {
  hookTimeout: 40000
}

It may be the solution then you have slow internet connection between laptop and db server

**Comment by mylastore** [comment]
SAVE...    error: Error: The hook `orm` is taking too long to load.

**Comment by fabienthetis** [comment]
It seems that you need to create a file config/orm.js
and set the following configuration: 
// config/orm.js
module.exports.orm = {
  _hookTimeout: 60000 // I used 60 seconds as my new timeout
};

I also found I had to change my pubsub timeout but that may not be necessary for you.

// config/pubsub.js
module.exports.pubsub = {
  _hookTimeout: 60000 // I used 60 seconds as my new timeout
};

Reference to the article:
 http://stackoverflow.com/questions/28524926/the-hook-orm-taking-too-long-to-load

**Comment by mylastore** [comment]
same

**Comment by fabienthetis** [comment]
Try also to update the lib mongodb : npm install mongodb --save

**Comment by fabienthetis** [comment]
Seems to be related to the adaptater sails-mongo.
Try  to set as adaptater mongo to check if you have the connection with mongodb.

mongodbServer: {
    adapter: 'mongo',
    host: 'localhost',
    port: 27017,
    // user: 'username',
    // password: 'password',
    database: 'ymple'
  },


In fact depending on your instance mongodb the sails-mongo is able or not to connect.

In the futur i will use directly mongo to have a better connection.

**Comment by fabienthetis** [comment]
I updated the version of sails-mongo@0.12.2
you can try npm install with this new package.json

**Comment by mylastore** [comment]
I downloaded your updated version and it works now 👍 thank you so much. Time to play around with ymple  ;- )

**Comment by mylastore** [comment]
so the database is been created automatically now

**Comment by fabienthetis** [comment]
So you can star Ymple ;- ) and play around it.

Cool! 

I will close the issue
