### ISSUE TITLE
Where are the detailed docs for this framework?

### ISSUE THREAD

**Issue by Makinsane** [Ymple/ymple-ecommerce#95]
Where are the detailed docs to make custom changes in this ecommerce framework. Is it scalable for large scale.

**Comment by fabienthetis** [comment]
A detailed documentation will be available soon here: https://www.ymple.com/doc/

**Comment by fabienthetis** [comment]
Now the details documentation is available at http://doc.ymple.com

**Comment by fabienthetis** [comment]
http://doc.ymple.com has been updated
